---
apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app: syncthing
spec:
  serviceName: syncthing
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: syncthing/syncthing:latest
          ports:
            - containerPort: 8384
              name: ui
            - containerPort: 22000
              name: sync
            - containerPort: 21027
              name: discovery
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /var/syncthing/config
              name: syncthing-config
            - mountPath: /var/syncthing/data
              name: syncthing-data
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /rest/system/ping
              port: 8384
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /rest/system/ping
              port: 8384
            initialDelaySeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-data
          persistentVolumeClaim:
            claimName: syncthing-data
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
  annotations:
    caddy.ingress/host: "syncthing.example.com"  # Replace with your actual domain
spec:
  selector:
    app: syncthing
  ports:
    - name: ui
      port: 8384
      targetPort: 8384
    - name: sync
      port: 22000
      targetPort: 22000
    - name: discovery
      port: 21027
      protocol: UDP
      targetPort: 21027
  type: ClusterIP