---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: linuxserver/lidarr:latest
          ports:
            - containerPort: 8686
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /config
              name: lidarr-config
            - mountPath: /music
              name: music
            - mountPath: /downloads
              name: downloads
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: music
          hostPath:
            path: /tank/media/music
            type: Directory
        - name: downloads
          hostPath:
            path: /tank/downloads
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
  annotations:
    caddy.ingress/host: "lidarr.example.com"  # Replace with your actual domain
spec:
  selector:
    app: lidarr
  ports:
    - port: 8686
      targetPort: 8686
  type: ClusterIP