---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          ports:
            - containerPort: 7878
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /movies
              name: movies
            - mountPath: /downloads
              name: downloads
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: movies
          hostPath:
            path: /tank/media/movies
            type: Directory
        - name: downloads
          hostPath:
            path: /tank/downloads
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
  annotations:
    caddy.ingress/host: "radarr.example.com"  # Replace with your actual domain
spec:
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
  type: ClusterIP