---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-operator
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-operator
subjects:
- kind: ServiceAccount
  name: tailscale-operator
  namespace: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-operator
  template:
    metadata:
      labels:
        app: tailscale-operator
    spec:
      serviceAccountName: tailscale-operator
      containers:
      - name: tailscale-operator
        image: tailscale/k8s-operator:latest
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TAILSCALE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: auth_key
        - name: TAILSCALE_TAILNET
          value: "example.com" # Replace with your tailnet name
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
data:
  # Replace with your Tailscale auth key encoded in base64
  # To generate: echo -n "your-tailscale-auth-key" | base64
  auth_key: "dGhpc19pc19hbl9leGFtcGxlX2F1dGhfa2V5" # Replace with actual base64 auth key